### ISSUE TITLE
Publication in PYPI

### ISSUE THREAD

**Issue by jcea** [dmeranda/httpheader#2]
Please, would you mind to release a PYPI version, installable using "pip" or similar?. Thanks a lot.

**Comment by nicholasserra** [comment]
I second this. Would be awesome to be able to grab this from pypi. Thanks!

**Comment by dmeranda** [comment]
My httpheader module is now published to PyPI.  See my project home page at:

```
http://deron.meranda.us/python/httpheader/
```

Or search PyPI for "httpheader".

Deron

On Thu, Apr 10, 2014 at 2:20 PM, Nicholas Serra notifications@github.comwrote:

> I second this. Would be awesome to be able to grab this from pypi. Thanks!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dmeranda/httpheader/issues/2#issuecomment-40119991
> .

## 

Deron Meranda
http://deron.meranda.us/
